### ISSUE TITLE
error: n is not defined (Has possible fix solution attached)

### ISSUE THREAD

**Issue by ArbestNew** [kartoteket/vue-image-upload-resize#15] opened 2019-03-30 12:05 UTC
After building a production version of my VUE app, the error throw "n is not defined". (No issue in dev version)

This issue only happens in .min.js: 
/dist/vue-image-upload-resize.umd.min.js

You can locate the error function by searching the following pattern (that's where I found the issue)
`{var i="";for(n=t;n<t+r;n++)i+=String.f`

I simply add `let` before the variable and the issue solved in my case. (I tested it in my production build.)

After my edit: 
`{var i="";for(let n=t;n<t+r;n++)i+=String.f`

Thank you again for your work, and I do appreciate it. Please consider my case and fix it, cause I believe it is a good VUE image uploader which is very helpful for so many possible projects.

**Comment by ArbestNew** [comment] 2019-03-31 04:04
The version I mentioned early is 2.0.4.

**Comment by svale** [comment] 2019-04-19 08:44
Hi @ArbestNew, thank you for noting this issue and for the proposed fix. And thank you for your patiences with my late reply. 

I believe the problem is inherited from the [exif-js](https://github.com/exif-js/) dependency, which it seems is no longer actively maintained (se e.g https://github.com/exif-js/exif-js/pull/50). I probably need to update a fork that better handles module loading/strict mode.

Until then I'll leave this issue open.

**Comment by memic84** [comment] 2019-06-12 10:05
Is there a other workaround, other than chaning the minified output file?

**Comment by svale** [comment] 2019-08-17 10:34
@ArbestNew og @memic84 thank your for you patience on this one. 

I'll be publishing av new version 2.1.0 with the exif utility inlined this weekend. That should resolve this issue. 

Thanks!

**Comment by svale** [comment] 2019-08-18 21:26
Resolved with [2.1.0](https://github.com/kartoteket/vue-image-upload-resize/releases/tag/v2.1.0) :)

**Closed by svale** 2019-08-18 21:26 UTC
